default:
  image: registry.gitlab.com/tankerhq/docker/node:latest
  tags:
    - linux
    - tanker

stages:
  - check
  - deploy

check:
  stage: check
  script:
    - poetry install
    - poetry run python run-ci.py check
  tags: [linux]

deploy:
  stage: deploy
  only:
    - master
  script:
    - poetry install
    - poetry run python run-ci.py deploy
  tags: [linux]
