[tool.poetry]
name = "filekit-tuto-app"
version = "0.1.0"
description = "FileKit tutorial application"
authors = ["Tanker staff <tech@tanker.io>"]

[tool.poetry.dependencies]
python = "^3.7"

ci = "2020.2.2093"
Faker = "^2.0.0"
ghp-import = "^0.5.5"
path = "^13.1.0"
pytest = "^5.3.5"
selenium = "^3.141.0"
tankersdk = "^2.2.3"


[[tool.poetry.source]]
name = "tanker.local"
url = "http://tanker.local:8181"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
